### ISSUE TITLE
Why empty

### ISSUE THREAD

**Issue by pingzhili** [tanzelin430/Computer-Architecture#1]

**Comment by tanzelin430** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi,Pingzhi!Glad to hear from you.Thanks for letting me know there is an empty repo in my GitHub, and I am now clearing my github homepage due to the issue you raised.Actually if you want to refer to previous lab source code and report, you may take a look at tanzelin430/CA_LAB-2021,which has lab2-lab4’s source code and already been deleted.I have just done updating the CA repo and now you can see all the lab source code and reports in Computer-Architecture.At last, a small piece of advice, cherish your time.Put all your efforts in your study when it is not too late though you have already got a very competetive GPA.USTC might be a good place to learn basic knowledge but definitely not a proper place for the basis of your life-long development.Keep studying harder and harder and wish you a good future in ZJU/FDU/NJU/RUC/THU/PKU.                                                                                                                                                Your friend Misaki                                                                                                                                                 2022/3/3
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                864109387
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/1/2022 ***@***.***> wrote： 





—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by pingzhili** [comment]
Thank you for your great-heating sharing
